# Form implementation generated from reading ui file 'UiFormats\arama_ekrani.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(934, 444)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UiFormats\\../assets/mba_logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        widget.setWindowIcon(icon)
        self.txt_hatamesaj = QtWidgets.QLabel(parent=widget)
        self.txt_hatamesaj.setGeometry(QtCore.QRect(0, 420, 931, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.txt_hatamesaj.setFont(font)
        self.txt_hatamesaj.setStyleSheet("color: rgb(255, 0, 0);")
        self.txt_hatamesaj.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_hatamesaj.setObjectName("txt_hatamesaj")
        self.tbl_aramalar = QtWidgets.QTableWidget(parent=widget)
        self.tbl_aramalar.setGeometry(QtCore.QRect(10, 91, 911, 321))
        self.tbl_aramalar.setLineWidth(1)
        self.tbl_aramalar.setAutoScrollMargin(16)
        self.tbl_aramalar.setRowCount(200)
        self.tbl_aramalar.setColumnCount(6)
        self.tbl_aramalar.setObjectName("tbl_aramalar")
        self.tbl_aramalar.horizontalHeader().setDefaultSectionSize(148)
        self.tbl_aramalar.verticalHeader().setDefaultSectionSize(22)
        self.lne_not = QtWidgets.QLineEdit(parent=widget)
        self.lne_not.setGeometry(QtCore.QRect(10, 50, 311, 24))
        self.lne_not.setObjectName("lne_not")
        self.btn_ekle = QtWidgets.QPushButton(parent=widget)
        self.btn_ekle.setGeometry(QtCore.QRect(330, 50, 311, 24))
        self.btn_ekle.setObjectName("btn_ekle")
        self.lne_tarih = QtWidgets.QDateTimeEdit(parent=widget)
        self.lne_tarih.setGeometry(QtCore.QRect(330, 20, 311, 25))
        self.lne_tarih.setObjectName("lne_tarih")
        self.lne_baslik = QtWidgets.QLineEdit(parent=widget)
        self.lne_baslik.setGeometry(QtCore.QRect(10, 20, 311, 24))
        self.lne_baslik.setObjectName("lne_baslik")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Aramalar"))
        self.txt_hatamesaj.setText(_translate("widget", "Hata Mesajı"))
        self.lne_not.setPlaceholderText(_translate("widget", "Görüşme Notu"))
        self.btn_ekle.setText(_translate("widget", "Ekle"))
        self.lne_baslik.setPlaceholderText(_translate("widget", "Görüşme Başlığı"))
