# Form implementation generated from reading ui file 'UiFormats\odeme.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(201, 331)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UiFormats\\../assets/mba_logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        widget.setWindowIcon(icon)
        self.lne_tutar = QtWidgets.QLineEdit(parent=widget)
        self.lne_tutar.setGeometry(QtCore.QRect(10, 190, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lne_tutar.setFont(font)
        self.lne_tutar.setText("")
        self.lne_tutar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lne_tutar.setObjectName("lne_tutar")
        self.btn_ekle = QtWidgets.QPushButton(parent=widget)
        self.btn_ekle.setGeometry(QtCore.QRect(10, 230, 181, 31))
        self.btn_ekle.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.58, x2:0, y2:0.6365, stop:0.136364 rgba(0, 255, 0, 255), stop:0.886364 rgba(0, 174, 152, 255));\n"
"color: rgb(255, 255, 255);\n"
"border:none;")
        self.btn_ekle.setObjectName("btn_ekle")
        self.i_ad = QtWidgets.QLabel(parent=widget)
        self.i_ad.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.i_ad.setFont(font)
        self.i_ad.setObjectName("i_ad")
        self.i_id = QtWidgets.QLabel(parent=widget)
        self.i_id.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.i_id.setObjectName("i_id")
        self.i_anlasilan = QtWidgets.QLabel(parent=widget)
        self.i_anlasilan.setGeometry(QtCore.QRect(10, 70, 51, 21))
        self.i_anlasilan.setObjectName("i_anlasilan")
        self.btn_cikar = QtWidgets.QPushButton(parent=widget)
        self.btn_cikar.setGeometry(QtCore.QRect(10, 270, 181, 31))
        self.btn_cikar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.461, y1:0.142045, x2:0.471, y2:1, stop:0 rgba(115, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"border:none;")
        self.btn_cikar.setObjectName("btn_cikar")
        self.i_odenen = QtWidgets.QLabel(parent=widget)
        self.i_odenen.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.i_odenen.setObjectName("i_odenen")
        self.txt_ad = QtWidgets.QLabel(parent=widget)
        self.txt_ad.setGeometry(QtCore.QRect(70, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txt_ad.setFont(font)
        self.txt_ad.setObjectName("txt_ad")
        self.txt_id = QtWidgets.QLabel(parent=widget)
        self.txt_id.setGeometry(QtCore.QRect(70, 40, 121, 21))
        self.txt_id.setObjectName("txt_id")
        self.txt_anlasilan = QtWidgets.QLabel(parent=widget)
        self.txt_anlasilan.setGeometry(QtCore.QRect(70, 70, 121, 21))
        self.txt_anlasilan.setObjectName("txt_anlasilan")
        self.txt_odenen = QtWidgets.QLabel(parent=widget)
        self.txt_odenen.setGeometry(QtCore.QRect(70, 100, 121, 21))
        self.txt_odenen.setObjectName("txt_odenen")
        self.txt_hatamesaj = QtWidgets.QLabel(parent=widget)
        self.txt_hatamesaj.setGeometry(QtCore.QRect(10, 310, 181, 16))
        self.txt_hatamesaj.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_hatamesaj.setObjectName("txt_hatamesaj")
        self.txt_gereken = QtWidgets.QLabel(parent=widget)
        self.txt_gereken.setGeometry(QtCore.QRect(70, 130, 121, 21))
        self.txt_gereken.setObjectName("txt_gereken")
        self.i_gereken = QtWidgets.QLabel(parent=widget)
        self.i_gereken.setGeometry(QtCore.QRect(10, 130, 51, 21))
        self.i_gereken.setObjectName("i_gereken")
        self.txt_tarih = QtWidgets.QLabel(parent=widget)
        self.txt_tarih.setGeometry(QtCore.QRect(70, 160, 121, 21))
        self.txt_tarih.setObjectName("txt_tarih")
        self.i_tarih = QtWidgets.QLabel(parent=widget)
        self.i_tarih.setGeometry(QtCore.QRect(10, 160, 51, 21))
        self.i_tarih.setObjectName("i_tarih")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Ödeme"))
        self.lne_tutar.setPlaceholderText(_translate("widget", "Tutar"))
        self.btn_ekle.setText(_translate("widget", "Ödenene Ekle"))
        self.i_ad.setText(_translate("widget", "Kişi Adı:"))
        self.i_id.setText(_translate("widget", "Kişi ID:"))
        self.i_anlasilan.setText(_translate("widget", "Anlaşılan:"))
        self.btn_cikar.setText(_translate("widget", "Ödenenden Çıkar"))
        self.i_odenen.setText(_translate("widget", "Ödenen:"))
        self.txt_ad.setText(_translate("widget", "Kişi Adı"))
        self.txt_id.setText(_translate("widget", "Kişi ID"))
        self.txt_anlasilan.setText(_translate("widget", "Anlaşılan"))
        self.txt_odenen.setText(_translate("widget", "Ödenen"))
        self.txt_hatamesaj.setText(_translate("widget", "Hata Mesajı"))
        self.txt_gereken.setText(_translate("widget", "Kalan"))
        self.i_gereken.setText(_translate("widget", "Kalan:"))
        self.txt_tarih.setText(_translate("widget", "Tarih"))
        self.i_tarih.setText(_translate("widget", "Tarih:"))
