# Form implementation generated from reading ui file 'UiFormats\sifre_giris.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        self.k_adi = QtWidgets.QLineEdit(parent=Form)
        self.k_adi.setGeometry(QtCore.QRect(150, 70, 300, 30))
        self.k_adi.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.k_adi.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.k_adi.setObjectName("k_adi")
        self.g_kodu = QtWidgets.QLineEdit(parent=Form)
        self.g_kodu.setGeometry(QtCore.QRect(150, 130, 300, 30))
        self.g_kodu.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.g_kodu.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.g_kodu.setObjectName("g_kodu")
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(-100, 240, 841, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.graphicsView_2.setFont(font)
        self.graphicsView_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.256, y1:0.562182, x2:1, y2:0.574, stop:0 rgba(26, 84, 0, 255), stop:1 rgba(91, 174, 0, 255));\n"
"")
        self.graphicsView_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(250, 240, 100, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView.setGeometry(QtCore.QRect(-50, -30, 741, 61))
        self.graphicsView.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.256, y1:0.562182, x2:1, y2:0.574, stop:0 rgba(26, 84, 0, 255), stop:1 rgba(91, 174, 0, 255));\n"
"")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.graphicsView.setObjectName("graphicsView")
        self.mdiArea = QtWidgets.QMdiArea(parent=Form)
        self.mdiArea.setGeometry(QtCore.QRect(-40, -80, 681, 451))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.VerPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setActivationOrder(QtWidgets.QMdiArea.WindowOrder.CreationOrder)
        self.mdiArea.setObjectName("mdiArea")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(214, 0, 176, 25))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.btn_onay = QtWidgets.QPushButton(parent=Form)
        self.btn_onay.setGeometry(QtCore.QRect(260, 190, 80, 25))
        self.btn_onay.setObjectName("btn_onay")
        self.info = QtWidgets.QLabel(parent=Form)
        self.info.setGeometry(QtCore.QRect(6, 220, 591, 20))
        self.info.setStyleSheet("color: rgb(255, 0, 0);")
        self.info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.info.setObjectName("info")
        self.mdiArea.raise_()
        self.k_adi.raise_()
        self.g_kodu.raise_()
        self.graphicsView_2.raise_()
        self.label.raise_()
        self.graphicsView.raise_()
        self.label_2.raise_()
        self.btn_onay.raise_()
        self.info.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.k_adi.setPlaceholderText(_translate("Form", "Kullanıcı Adını Giriniz"))
        self.g_kodu.setPlaceholderText(_translate("Form", "Giriş Kodunu Giriniz"))
        self.label.setText(_translate("Form", "MBA"))
        self.label_2.setText(_translate("Form", "Güvenlik Duvarı"))
        self.btn_onay.setText(_translate("Form", "Onay"))
        self.info.setText(_translate("Form", "INFORMATİON"))
